    1 operator
      1 webapp
      1 app
      1 oracle
      2 db1inst1
      4 zznode
      1 zxin10
      1 zxin20
      4 ftpuser
      3 oracle
      1 bwadmin
      1 cacti
      1 test1
      1 ovidiu
      1 aaa
      1 git
      1 deploy
      1 user
      1 postgres
      2 Soporte
      1 nagios
      1 oracle
     11 heslo
     27 cacti
     12 cactiuser
     28 hadoop
     14 nagios
     11 prueba
      1 ihor
      1 prueba
      6 postgres
      9 squid
     13 office
      9 postgres
     22 hadoop
     14 kiosk
     12 glassfish
      4 prove
      4 sinaq
      4 prova
      3 testi
     12 teamspeak
     12 vmail
      1 prueba
      5 ivan
      1 igor
      2 test1
      1 test2
      3 user1
      1 user2
      1 test1
      1 postgres
      1 git
      1 nagios
      2 test
      1 guest
      1 web
      1 sadmin
      1 alex
      1 mass
      1 mov
      1 web
      1 bang
      1 claude
      1 libb
      1 madmaxx
      1 NpC
      1 amstrad
      1 sniff
      1 tool
      1 PruncuTz
      1 nagios
      1 http
      1 last
      1 user
      1 plesk
      1 toor
      1 douglas
      1 gabi
    363 [preauth]